name: Test and Lint

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test-and-lint:
    runs-on: ubuntu-latest
    services:
      mongo:
        image: mongo:4.4
        ports:
          - 27017:27017

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm ci

      - name: Run ESLint
        run: |
          npx eslint . --ext .js

      - name: Run Jest tests with coverage
        run: |
          npm test -- --coverage

      - name: Install Selenium Side Runner
        run: |
          npm install -g selenium-side-runner

      - name: Run Selenium Test
        run: |
          selenium-side-runner -c "browserName=chrome goog:chromeOptions.args=[headless,disable-gpu,no-sandbox]" tests/selenium/test_Orig.side
