name: Test and Lint

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test-and-lint:
    runs-on: ubuntu-latest
    services:
      mongo:
        image: mongo:4.4
        ports:
          - 27017:27017

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm ci

      - name: Run ESLint
        run: |
         npx eslint . --fix --ignore-pattern tests/k6/

      - name: Run Jest tests with coverage
        run: |
          npm test -- --coverage

      - name: Install Node.js dependencies
        run: npm install

      - name: Start your server (node server.js)
        run: |
          node server.js &
          sleep 5

      - name: Install Selenium Side Runner
        run: |
          npm install -g selenium-side-runner

      - name: Run Selenium Test
        run: |
          selenium-side-runner -c "browserName=chrome goog:chromeOptions.args=[headless,disable-gpu,no-sandbox]" tests/selenium/test_Orig.side

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install selenium semgrep

      - name: Run Semgrep Scan
        run: semgrep --config auto .

      - name: Install Chrome and WebDriver
        run: |
          sudo apt update
          sudo apt install -y wget unzip
          wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
          sudo apt install -y ./google-chrome-stable_current_amd64.deb

          CHROME_VERSION=$(google-chrome --version | grep -oP '\d+\.\d+\.\d+\.\d+')
          CHROMEDRIVER_VERSION=$(curl -s "https://googlechromelabs.github.io/chrome-for-testing/last-known-good-versions-with-downloads.json" | jq -r --arg ver "$CHROME_VERSION" '.channels.Stable.downloads.chromedriver[] | select(.platform == "linux64") | .url')
          wget -O chromedriver.zip "$CHROMEDRIVER_VERSION"
          unzip chromedriver.zip
          sudo mv chromedriver-linux64/chromedriver /usr/local/bin/
          sudo chmod +x /usr/local/bin/chromedriver

      - name: Run test script
        run: python ./tests/SeleniumWebDriver/test_register_and_login.py

      - name: Run Behevour Driven Testing
        run: npx cucumber-js tests/cucumber/user-auth.feature

